// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert'];
    AAvatar: typeof import('@arco-design/web-vue')['Avatar'];
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb'];
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem'];
    AButton: typeof import('@arco-design/web-vue')['Button'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADoption: typeof import('@arco-design/web-vue')['Doption'];
    ADrawer: typeof import('@arco-design/web-vue')['Drawer'];
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown'];
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber'];
    ALayout: typeof import('@arco-design/web-vue')['Layout'];
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent'];
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter'];
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASwitch: typeof import('@arco-design/web-vue')['Switch'];
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip'];
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
